title: INF ROZOWI
description: Projekt w ramach przedmiotu "Programowania zespołowego" - Różowi.  Temat: System zarządzania zadaniami w zespole informatycznym.
GitHub Stars: https://github.com/PZ-2025/INF_ROZOWI
icon: ./Docs/img/logo.png
favicon: "./Docs/img/logo.png"
show_downloads: true
theme: jekyll-theme-midnight
# github:
#   zip_url: https://py.dawidolko.pl/download.zip
#   another_url: another value
